#!/usr/bin/env python3
"""Reproduce every quantitative statement of Assal et al. (2025) from the paper's own tables.

The paper is a qualitative interview study: its transcripts are not public, so the
coding itself cannot be re-run. What CAN be reproduced is every number the paper
derives from its published tables:
  * Table 1  (per-participant demographics)       -> mean / median experience, counts
  * Table B1 (who mentioned which learning activity) -> counts per activity / type / initiator
Data below were transcribed by hand from the published PDF (doi:10.1093/cybsec/tyaf005,
CC BY-NC 4.0) and checked twice. Output: docs/PAPER_REPRODUCTION.md

  python scripts/reproduce_paper_stats.py
"""
from __future__ import annotations

import statistics as st
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# --- Table 1: id, gender, age, years of experience, self-rated security knowledge (SK), company size, team size
TABLE1 = [
    ("P1", "F", 30, 1, 4, "Large", 20), ("P2", "M", 34, 15, 5, "Large", 12),
    ("P3", "M", 33, 10, 4, "Large", 10), ("P4", "M", 38, 21, 4, "SME", 7),
    ("P5", "M", 34, 12, 5, "Large", 7), ("P6", "F", 26, 3, 3, "Large", 12),
    ("P7", "M", 33, 4, 4, "SME", 3), ("P8", "M", 34, 5, 3, "Large", 20),
    ("P9", "M", 33, 8, 2, "SME", 5), ("P10", "M", 37, 20, 5, "SME", 10),
    ("P11", "M", 38, 15, 2, "SME", 8), ("P12", "M", 26, 3, 2, "SME", 4),
    ("P13", "F", 27, 5, 4, "Large", 7),
]

# --- Table B1: (learning type, initiator, activity) -> participants exactly as printed
TABLE_B1 = [
    ("Formal", "Employer", "Attending mandatory training", ["P1", "P2", "P5"]),
    ("Semi-formal", "Employer", "Receiving in-context support", ["P1", "P4", "P6", "P7", "P9", "P10"]),
    ("Semi-formal", "Employer", "Using code review as a learning tool", ["P1", "P4", "P6", "P9"]),
    ("Informal", "Employer", "Participating in mediated social contact opportunities",
     ["P2", "P6", "P7", "P9", "P11", "P10", "P11"]),          # P11 printed twice in the paper
    ("Formal", "Employer & Developer", "Attending employer-sponsored talks", ["P2", "P3"]),
    ("Formal", "Employer & Developer", "Referring to optional material", ["P1", "P3", "P9"]),
    ("Semi-formal", "Employer & Developer", "Attending conferences", ["P2", "P3", "P5", "P9"]),
    ("Informal", "Employer & Developer", "Collaborating in the workplace", ["P1", "P2", "P3", "P5", "P6", "P7", "P9"]),
    ("Formal", "Developer", "Taking courses", ["P4", "P6", "P9"]),
    ("Semi-formal", "Developer", "Searching online", ["P3", "P8", "P9"]),
    ("Semi-formal", "Developer", "Reading information and discussion websites", ["P4", "P7", "P9", "P10"]),
    ("Informal", "Developer", "Seeking help", ["P1", "P2", "P4", "P7", "P8", "P9", "P10"]),
]

# --- Quantitative statements made in the paper's text (section, claim, reported value)
CLAIMS = [
    ("Study design", "Participants", 13),
    ("Study design", "Interviews in person", 3),
    ("Study design", "Interviews remote", 10),
    ("Participant demographics", "Mean years of development experience", 9.35),
    ("Participant demographics", "Median years of development experience (Md)", 8),
    ("Formal learning", "Participants who attended mandatory training", 3),
]


def spearman(x: list[float], y: list[float]) -> float:
    def ranks(v):
        order = sorted(range(len(v)), key=lambda i: v[i])
        r = [0.0] * len(v)
        i = 0
        while i < len(v):
            j = i
            while j + 1 < len(v) and v[order[j + 1]] == v[order[i]]:
                j += 1
            for k in range(i, j + 1):
                r[order[k]] = (i + j) / 2 + 1
            i = j + 1
        return r
    rx, ry = ranks(x), ranks(y)
    mx, my = st.fmean(rx), st.fmean(ry)
    num = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
    den = (sum((a - mx) ** 2 for a in rx) * sum((b - my) ** 2 for b in ry)) ** 0.5
    return num / den


def main() -> None:
    years = [r[3] for r in TABLE1]
    sk = [r[4] for r in TABLE1]
    unique = {act: sorted(set(p), key=lambda s: int(s[1:])) for _, _, act, p in TABLE_B1}
    recomputed = {
        "Participants": len(TABLE1),
        "Interviews in person": 3,           # stated only in text; no per-participant column
        "Interviews remote": 10,
        "Mean years of development experience": round(st.fmean(years), 2),
        "Median years of development experience (Md)": st.median(years),
        "Participants who attended mandatory training": len(unique["Attending mandatory training"]),
    }
    md = ["# Reproduction of the paper's quantitative statements", "",
          "Source: Assal et al., *Software security in practice: knowledge and motivation*, "
          "Journal of Cybersecurity 11(1), tyaf005, 2025 (CC BY-NC 4.0). Generated by "
          "`scripts/reproduce_paper_stats.py` from Table 1 and Table B1 as printed in the paper.", "",
          "## 1. Statements in the text vs. values recomputed from the paper's tables", "",
          "| Section | Statement | Reported | Recomputed | Match |", "|---|---|---|---|---|"]
    for sec, claim, rep in CLAIMS:
        rec = recomputed[claim]
        ok = "✅" if abs(float(rep) - float(rec)) < 0.005 else "⚠️ differs"
        if claim.startswith("Interviews"):
            ok = "— (no per-participant data)"
        md.append(f"| {sec} | {claim} | {rep} | {rec} | {ok} |")
    md += ["", f"Experience values (Table 1): {sorted(years)} → sum {sum(years)}, n = {len(years)}, "
           f"mean = {sum(years)}/{len(years)} = **{st.fmean(years):.4f}**. The paper reports 9.35. "
           "Rounding and truncation both give 9.38, so 9.35 cannot come from Table 1 as printed. "
           "Most likely a typo, or one Table 1 value differs from the data used for the text. "
           "The median (8) matches.", ""]

    g = Counter(r[1] for r in TABLE1)
    cs = Counter(r[5] for r in TABLE1)
    md += ["## 2. Descriptive statistics recomputed from Table 1", "",
           "| Variable | Value |", "|---|---|",
           f"| Gender | {g['F']} female, {g['M']} male |",
           f"| Age | {min(r[2] for r in TABLE1)}–{max(r[2] for r in TABLE1)} (mean {st.fmean(r[2] for r in TABLE1):.1f}) |",
           f"| Years of experience | {min(years)}–{max(years)}, mean {st.fmean(years):.2f}, median {st.median(years)}, sd {st.stdev(years):.2f} |",
           f"| Self-rated security knowledge (1–5) | {min(sk)}–{max(sk)}, median {st.median(sk)}, mean {st.fmean(sk):.2f} |",
           f"| Company size | {cs['Large']} large enterprise, {cs['SME']} SME |",
           f"| Team size | {min(r[6] for r in TABLE1)}–{max(r[6] for r in TABLE1)}, median {st.median(r[6] for r in TABLE1)} |", ""]

    md += ["## 3. Table B1 recomputed: mentions per learning activity", "",
           f"Table B1 lists {len(TABLE_B1)} learning activities (counted by us; the text gives no total).", "",
           "| Type | Initiator | Activity | Participants | n |", "|---|---|---|---|---|"]
    for typ, ini, act, plist in TABLE_B1:
        dup = " (P11 listed twice in the paper)" if len(plist) != len(set(plist)) else ""
        md.append(f"| {typ} | {ini} | {act} | {', '.join(unique[act])}{dup} | {len(unique[act])} |")

    by_type = {t: sum(len(unique[a]) for tt, _, a, _ in TABLE_B1 if tt == t) for t in ("Formal", "Semi-formal", "Informal")}
    ppl_type = {t: sorted({p for tt, _, a, _ in TABLE_B1 if tt == t for p in unique[a]}, key=lambda s: int(s[1:]))
                for t in by_type}
    by_ini = {i: sum(len(unique[a]) for _, ii, a, _ in TABLE_B1 if ii == i) for i in ("Employer", "Employer & Developer", "Developer")}
    mentioned = {p for a in unique.values() for p in a}
    per_p = Counter(p for a in unique.values() for p in a)
    total = sum(by_type.values())
    md += ["", "## 4. Checking the paper's qualitative claim with its own Table B1", "",
           "Claim (Abstract / Discussion): developers *favoured in-context (semi-formal and informal) learning*.", "",
           "| Learning type | Activities | Mentions | Share | Distinct participants |", "|---|---|---|---|---|"]
    for t, n in by_type.items():
        k = sum(1 for tt, *_ in TABLE_B1 if tt == t)
        md.append(f"| {t} | {k} | {n} | {100 * n / total:.0f}% | {len(ppl_type[t])} |")
    md += ["", f"Semi-formal + informal = {by_type['Semi-formal'] + by_type['Informal']}/{total} mentions "
           f"({100 * (by_type['Semi-formal'] + by_type['Informal']) / total:.0f}%) vs formal {by_type['Formal']}/{total}. "
           "The table is **consistent** with the claim, although B1 counts *mentions*, not preferences.", "",
           "| Initiator | Mentions |", "|---|---|"] + [f"| {i} | {n} |" for i, n in by_ini.items()]
    silent = [r[0] for r in TABLE1 if r[0] not in mentioned]
    md += ["", f"- Participants appearing in Table B1: {len(mentioned)}/13. **Not listed at all: {', '.join(silent)}**.",
           f"- Mentions per participant (B1): " + ", ".join(f"{p}={per_p[p]}" for p in sorted(per_p, key=lambda s: int(s[1:]))) + ".",
           f"- P9 appears in {per_p['P9']}/12 activities, which makes the table dominated by one participant.", ""]

    exp_by_p = {r[0]: r[3] for r in TABLE1}
    sk_by_p = {r[0]: r[4] for r in TABLE1}
    ids = [r[0] for r in TABLE1]
    md += ["## 5. Additional analysis (ours, exploratory, n = 13)", "",
           f"- Spearman ρ(years of experience, self-rated SK) = **{spearman([exp_by_p[i] for i in ids], [sk_by_p[i] for i in ids]):.2f}**.",
           f"- Spearman ρ(self-rated SK, number of learning activities mentioned) = "
           f"**{spearman([sk_by_p[i] for i in ids], [per_p.get(i, 0) for i in ids]):.2f}**.",
           "- With n = 13 these are descriptive only; no significance is claimed.", "",
           "## 6. What cannot be reproduced", "",
           "- The coding (170 codes / 600 excerpts) and the themes: interview transcripts are not published.",
           "- Table C1 (motivation codes) gives definitions and quotes, not counts.",
           "- Hence the DT074 project reproduces the paper **selectively**: its findings become design "
           "requirements and testable hypotheses (docs/PAPER_MAPPING.md), measured on NIST SARD.", ""]
    out = ROOT / "docs" / "PAPER_REPRODUCTION.md"
    out.write_text("\n".join(md), encoding="utf-8", newline="\n")
    print("\n".join(md))


if __name__ == "__main__":
    main()
